services:
  db:
    image: postgres:17-alpine
    container_name: vanlife_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - vanlife_data:/var/lib/postgresql/data
    env_file: .env

volumes:
  vanlife_data:
